[custom]

; ========= 规则（顺序=优先级） =========

; 核心私有/高频服务
ruleset=🌐 TRDR,https://raw.githubusercontent.com/LUCK777777/clash-rule/refs/heads/main/rule/trdr.list
ruleset=🤖 AIGC,[]DOMAIN-SUFFIX,perplexity.ai
ruleset=🤖 AIGC,[]DOMAIN-SUFFIX,pplx.ai
ruleset=💱 交易所,https://raw.githubusercontent.com/LUCK777777/clash-rule/refs/heads/main/rule/binance.list

; 私网直连
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs

; GitHub
ruleset=🐙 GitHub,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs

; AI 服务
ruleset=🤖 AIGC,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/openai.mrs
ruleset=🤖 AIGC,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs

; 社交媒体
ruleset=🕊️ Twitter,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs
ruleset=🕊️ Twitter,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs

; 视频（YouTube 必须先于 Google）
ruleset=📹 YouTube,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs

; Google
ruleset=📱 Google,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
ruleset=📱 Google,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs

; 即时通讯
ruleset=📲 Telegram,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
ruleset=📲 Telegram,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs

; 流媒体
ruleset=🎥 Netflix,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
ruleset=🎥 Netflix,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs
ruleset=🎬 Disney+,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs
ruleset=🎵 Spotify,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs
ruleset=📱 TikTok,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs

; 系统服务
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs
ruleset=💳 PayPal,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml

; 大陆直连
ruleset=💬 WeChat,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-cn.mrs
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs

; 其余境外兜底
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitch.mrs
ruleset=🇹🇼 台湾节点,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.mrs
ruleset=💬 Discord,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/discord.mrs
ruleset=🎮 游戏平台,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs
ruleset=🚀 节点选择,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-!cn.mrs
ruleset=🚀 节点选择,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs
ruleset=🚀 节点选择,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs

; IP 防泄漏兜底
ruleset=🎯 全球直连,https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs

; 终极兜底
ruleset=🚀 节点选择,[]FINAL


; ========= 策略组 =========

; 自建节点
custom_proxy_group=🛠 自建节点`select`(DIY|自建|VPS|MyNode|Self|NAT)

; 入口与常用
custom_proxy_group=🚀 节点选择`select`[]🛠 自建节点`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=♻️ 自动选择`url-test`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`https://cp.cloudflare.com/generate_204`300,,50

; 业务策略组
custom_proxy_group=🤖 AIGC`select`[]🛠 自建节点`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]DIRECT
custom_proxy_group=🐙 GitHub`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=📱 Google`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=📹 YouTube`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=📲 Telegram`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🎥 Netflix`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇸🇬 狮城节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🎬 Disney+`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🎵 Spotify`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=📱 TikTok`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🕊️ Twitter`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=💬 Discord`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🛠 自建节点`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🛠 自建节点`[]🚀 节点选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点
custom_proxy_group=💳 PayPal`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇺🇲 美国节点`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]DIRECT
custom_proxy_group=💬 WeChat`select`[]DIRECT`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点
custom_proxy_group=🎮 游戏平台`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=💱 交易所`select`[]🛠 自建节点`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港节点`[]🇸🇬 狮城节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🇺🇲 美国节点`[]DIRECT
custom_proxy_group=🌐 TRDR`select`(.*)`[]DIRECT

; 辅助
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🛠 自建节点`[]🚀 节点选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT

; 地区自动测速（测速地址换成 cloudflare，脱离 Google 链路）
custom_proxy_group=🇭🇰 香港节点`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong|HKG)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本节点`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan|Tokyo|NRT|KIX)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国节点`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|ATL|BUF|DFW|EWR|IAD|LAX|MCI|MIA|ORD|PHX|PDX|SEA|SJC)`https://cp.cloudflare.com/generate_204`300,,150
custom_proxy_group=🇹🇼 台湾节点`url-test`(台|新北|彰化|TW|Taiwan|TPE|KHH)`https://cp.cloudflare.com/generate_204`300,,50
custom_proxy_group=🇸🇬 狮城节点`url-test`(新加坡|坡|狮城|SG|Singapore|SIN)`https://cp.cloudflare.com/generate_204`300,,50

enable_rule_generator=true
overwrite_original_rules=true
